### ISSUE TITLE
Data download gives "error 3"

### ISSUE THREAD

**Issue by mpi-pebert** [MPIIComputationalEpigenetics/DeepBlue-Web#148]
I wanted to download ENCODE TF ChIP-seq data for mm9; after making my selection (all peak files) and proceeding to the download page, I clicked on "Request Download" and got a pop-up telling me "error 3", nothing else.
Browser is Firefox 53.0.3

**Comment by felipealbrecht** [comment]
Hello Peter,

please, may you give me more details:
 - How many files did you select?
 - Did you wait for the Download page (the page that you click after selecting the data) to load all the fields for selection?

I just tested with a smaller subset (4 TFs) and it looks that it works fine.

**Comment by felipealbrecht** [comment]
Hello, I tested again selecting the data with the grid page and downloading.

The request is:
http://deepblue.mpi-inf.mpg.de/request.php?_id=r818493

btw: I am testing with Chrome 59

**Comment by mpi-pebert** [comment]
The number of experiments is 296. I selected the meta columns epigenetic mark, biosource, project, sample_id, name.

I canceled the operation and started again - same output "error 3".

**Comment by felipealbrecht** [comment]
Please, check your javascript console and paste any useful information.
(Errors/warnings)

**Comment by felipealbrecht** [comment]
I found the error.
I will work on this during the week.

For now, you can select the data in smaller groups (I think that 2 groups
of ~150 files is enough, if not, please, 3 groups of ~100 files each)

Sorry for the inconvenience.

**Comment by mpi-pebert** [comment]
Ok - according to the console output, it's a 414 URI too large

**Comment by felipealbrecht** [comment]
Bug fixed.

Btw, I did a request with the informed parameters and it is being processed.

You can access the request here: http://deepblue.mpi-inf.mpg.de/request.php?_id=r818495
